### ISSUE TITLE
Проверка бустинг

### ISSUE THREAD

**Issue by KochetovNicolai** [Tismoney/MIPT_Data_Mining_In_Action_2016#1]
Привет!

1. Вопрос 3. Целевая переменная - это значение (анти)градиента функции потерь.
2. `grad = -special.expit(original_y * pred_y) * original_y` Потерялся минус в аргументе функции expit
3. `estimator.fit(X, self._predict(X) - self.lr * grad)` - снова, как и в пункте 1, целевая переменная - это антиградиент. `self._predict(X)` здесь лишний. Вообще, мне кажется, что это было сделано глядя на итоговое качество. Действительно, если расписать выражение `self._predict(X) - self.lr * grad` с градиентом из 2, то получится почти то, что нужно (не совсем :).

В остальном, кажется, все нормально. Бустинг засчитываю.

**Comment by Tismoney** [comment]
Привет!

Понял в чем была проблема. Исправил. 

Спасибо большое.
